# Use root/example as user/password credentials
version: '3.1'

services:
  ## mysql Database service image
  db-music-player:
    image: mysql:5.7
    restart: always
    container_name: db-music-player
    environment:
      MYSQL_DATABASE: music_player
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_TCP_PORT: 3307
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./my-db:/var/lib/mysql

  mysql-workbench:
    image: ghcr.io/linuxserver/mysql-workbench
    container_name: mysql-workbench
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /path/to/config:/config
    ports:
      - 3000:3000
    cap_add:
      - IPC_LOCK
    restart: unless-stopped


## server image
  api-music-player:
    build:
      context: ./server
      dockerfile: Dockerfile
    stdin_open: true
    container_name: api-music-player
    volumes:
      - ./server:/usr/app/server
      - '/usr/app/server/node_modules'
    ports:
      - '8080:8080'
    environment:
      HOST: "db-music-player" ## same as the database service name
      PORT: 8080
      PASSWORD: "password"
      DATABASE: "music_player"
      TOKEN_SECRET: "6f8df0642f85304b486f5d0a32fb30e3b6fda446b3c2dc253ab2daf0b9ddf7ccbe1cfdfbb19ce9d980b75e922fec053833cfa2fa03d6e21f7d2be223d4fb79c8"
      MYSQL_PORT: 3307
    depends_on:
      - db-music-player 


## client image
  app-music-player:
    build:
      context: ./client
      dockerfile: Dockerfile
    stdin_open: true
    container_name: app-music-player
    volumes:
      - ./client:/usr/app/client
      - '/usr/app/client/node_modules'
    ports:
      - '3030:3000'
    depends_on:
      - api-music-player ## server image

volumes:
  db-music-player:
    driver: local
